### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by VulcanBirdy** [FuckingToasters/OTP-Verification-Bot#1]
Failed to load extension ban_order.py
Traceback (most recent call last):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 715, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\ban_order.py", line 13, in <module>
    class ban_activation_number(commands.Cog):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\ban_order.py", line 18, in ban_activation_number
    async def ban_order(self, ctx, order_id):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\cog_ext.py", line 63, in wrapper
    opts = manage_commands.generate_options(cmd, desc, connector)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\utils\manage_commands.py", line 313, in generate_options
    SlashCommandOptionType.from_type(param.annotation) or SlashCommandOptionType.STRING
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 480, in from_type
    if issubclass(t, discord.abc.User):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\typing.py", line 1212, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\main.py", line 47, in <module>
    discordbot.load_extension(f"Cogs.{filename[:-3]}")
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 787, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 718, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'Cogs.ban_order' raised an error: TypeError: Protocols with non-method members don't support issubclass()
Failed to load extension cancel_order.py
Traceback (most recent call last):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 715, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\cancel_order.py", line 13, in <module>
    class cancel_activation_number(commands.Cog):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\cancel_order.py", line 18, in cancel_activation_number
    async def cancel_order(self, ctx, order_id):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\cog_ext.py", line 63, in wrapper
    opts = manage_commands.generate_options(cmd, desc, connector)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\utils\manage_commands.py", line 313, in generate_options
    SlashCommandOptionType.from_type(param.annotation) or SlashCommandOptionType.STRING
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 480, in from_type
    if issubclass(t, discord.abc.User):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\typing.py", line 1212, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\main.py", line 47, in <module>
    discordbot.load_extension(f"Cogs.{filename[:-3]}")
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 787, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 718, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'Cogs.cancel_order' raised an error: TypeError: Protocols with non-method members don't support issubclass()
[>] Cogs.checkapi loaded
[>] Cogs.cryptoprice loaded
Failed to load extension finish_order.py
Traceback (most recent call last):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 715, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\finish_order.py", line 18, in <module>
    class finish_activation_number(commands.Cog):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\finish_order.py", line 23, in finish_activation_number
    async def finish_order(self, ctx, order_id):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\cog_ext.py", line 63, in wrapper
    opts = manage_commands.generate_options(cmd, desc, connector)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\utils\manage_commands.py", line 313, in generate_options
    SlashCommandOptionType.from_type(param.annotation) or SlashCommandOptionType.STRING
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 480, in from_type
    if issubclass(t, discord.abc.User):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\typing.py", line 1212, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\main.py", line 47, in <module>
    discordbot.load_extension(f"Cogs.{filename[:-3]}")
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 787, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 718, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'Cogs.finish_order' raised an error: TypeError: Protocols with non-method members don't support issubclass()
Failed to load extension ordernumber.py
Traceback (most recent call last):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 715, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\ordernumber.py", line 18, in <module>
    class order_activation_number(commands.Cog):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\ordernumber.py", line 24, in order_activation_number
    async def buy_activation_number(self, ctx, service, country, operator):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\cog_ext.py", line 63, in wrapper
    opts = manage_commands.generate_options(cmd, desc, connector)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\utils\manage_commands.py", line 313, in generate_options
    SlashCommandOptionType.from_type(param.annotation) or SlashCommandOptionType.STRING
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 480, in from_type
    if issubclass(t, discord.abc.User):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\typing.py", line 1212, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\main.py", line 47, in <module>
    discordbot.load_extension(f"Cogs.{filename[:-3]}")
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 787, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 718, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'Cogs.ordernumber' raised an error: TypeError: Protocols with non-method members don't support issubclass()
[>] Cogs.paymenthistory loaded
Failed to load extension setapi.py
Traceback (most recent call last):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 715, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\setapi.py", line 15, in <module>
    class mongodb(commands.Cog):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\Cogs\setapi.py", line 21, in mongodb
    async def set_apikey(self, ctx, api_key):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\cog_ext.py", line 63, in wrapper
    opts = manage_commands.generate_options(cmd, desc, connector)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\utils\manage_commands.py", line 313, in generate_options
    SlashCommandOptionType.from_type(param.annotation) or SlashCommandOptionType.STRING
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 480, in from_type
    if issubclass(t, discord.abc.User):
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\typing.py", line 1212, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luxury\Desktop\OTP-Verification-Bot-main\main.py", line 47, in <module>
    discordbot.load_extension(f"Cogs.{filename[:-3]}")
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 787, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\luxury\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 718, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'Cogs.setapi' raised an error: TypeError: Protocols with non-method members don't support issubclass()
[>] Cogs.userinfo loaded
[>] Discordbot is ready!

**Comment by FuckingToasters** [comment]
This is because the Developers of the Slashcommand LIbary have chnaged some things and the one which is in use is not working anymore and the code needs to be updated by me. i'll start updating the code and push a new working version. thanks for letting me know.

**Comment by VulcanBirdy** [comment]
Is there a rough ETA of when it will be fixed?

**Comment by FuckingToasters** [comment]
> Is there a rough ETA of when it will be fixed?

sry for my late response. i'm currently working on some other projects but as soon as they r done i will make this one working again.
